on:
  push:
    branches: [main]

jobs:
  sign-the-exe:
    runs-on: windows-latest
    name: Sign the executable file

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      # The .NET restore and build steps have been removed.

      - name: Sign the file with Trusted Signing
        uses: azure/trusted-signing-action@v0
        with:
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          endpoint: https://eus.codesigning.azure.net/
          code-signing-account-name: vscx-codesigning
          certificate-profile-name: vscx-certificate-profile
          
          # 1. Point to the root folder of the repository
          files-folder: ${{ github.workspace }}
          
          # 2. Filter for only the .exe file 
          files-folder-filter: exe
          
          timestamp-rfc3161: http://timestamp.acs.microsoft.com